include ../include/make.inc

NAME = garywiz/chaperone-lamp
VERSION = 0.1.5.0		# C.C.C.X where C.C.C is chaperone version used in this release

.PHONY: all build binaries

all: build

build:
	$(DOCKER_BUILD)

rebuild:
	$(DOCKER_REBUILD)
