#!/bin/bash
# If our host has an apt proxy container running at 3142, then use it for apt
# This is a nice way to optimize builds.  Just 
#   docker run sameersbn/apt-cacher-ng -p 3142:3142 and then your installs can use
# the proxy to speed things up.

defhost=`ip route | awk '/default/ { print $3; }'`

if [ "$1" == "off" -o ! -x /bin/nc ]; then
   rm -f /etc/apt/apt.conf.d/01proxy
   echo Note: apt-get proxy not in use
   exit
fi

if nc -z $defhost 3142; then
   echo "Acquire::http { Proxy \"http://$defhost:3142\"; };" >/etc/apt/apt.conf.d/01proxy
   echo Note: Found apt-get proxy on $defhost:3142
else
   rm -f /etc/apt/apt.conf.d/01proxy
   echo Note: Did not find apt-get proxy on $defhost:3142
fi
